######################################
######                          ######
######         FRAGMENTS        ######
######                          ######
######################################

fragment BotCard on BotObject {
  avatar
  shortDescription
  name
  tags {
    displayName
  }
  id
  guildCount
  votes {
    totalCount
  }
  certified
  inviteLink
}

######################################
######                          ######
######           BOTS           ######
######                          ######
######################################

# Type
query BotCards($pagination: PaginationInput) {
  bots(pagination: $pagination) {
    nodes {
      ...BotCard
    }
  }
}

# Query for home bots
query HomeBots {
  mostVoted: bots(pagination: { size: 4, sortOrder: DESC, sortBy: "votes" }) {
    nodes {
      ...BotCard
    }
  }
  mostBig: bots(pagination: { size: 4, sortOrder: DESC, sortBy: "guildCount" }) {
    nodes {
      ...BotCard
    }
  }
  mostRecent: bots(pagination: { size: 4, sortOrder: DESC, sortBy: "createdAt" }) {
    nodes {
      ...BotCard
    }
  }
}

# Query for a single bot
query SingleBot($input: GetBotInput!) {
  getBot(input: $input) {
    avatar
    banner
    certified
    description
    website
    supportServer
    status
    shortDescription
    prefix
    github
    guildCount
    id
    importedFrom
    inviteLink
    createdAt
    name
    votes {
      totalCount
    }
    owners {
      username
      id
      avatar
    }
    tags {
      displayName
      id
    }
  }
}

# Query to search bots
query SearchBots($pagination: PaginationInput, $input: SafeFiltersInput) {
  bots(pagination: $pagination, input: $input) {
    totalCount
    nodes {
      id
      avatar
      name
      shortDescription
    }
  }
}


# Query for a single bot vote information
query SingleBotVote($input: GetBotInput!) {
  getBot(input: $input) {
    avatar
    id
    name
    votes {
      totalCount
    }
    guildCount
    certified
  }
}

# Query to check if user can vote a bot
query CanVote($input: BotVoteCreateInput!) {
  canVote(input: $input) {
    canVote
    expires
  }
}

# Query to get bot webhook
query Webhook($input: GetWebhookInput!) {
  getWebhook(input: $input) {
    id
    events
    payloadFields
    secret
    url
  }
}

# Query to get bots for the admin panel
query PanelBots($input: FiltersBotInput) {
  panelBots(input: $input) {
    totalCount
    nodes {
      avatar
      owners {
        avatar
        id
        username
      }
      id
      name
      status
    }
  }
}

######################################
######                          ######
######          USERS           ######
######                          ######
######################################

# Query to get a user
query GetUser($input: GetUserInput!) {
  getUser(input: $input) {
    avatar
    bio
    id
    username
    banner
    bots {
      ...BotCard
    }
  }
}

######################################
######                          ######
######           TAGS           ######
######                          ######
######################################

# Query to get tags
query GetTags {
  tags {
    nodes {
      bots {
        totalCount
      }
      displayName
      id
    }
  }
}

######################################
######                          ######
######           MISC           ######
######                          ######
######################################

# Query to get session
query Session {
  me {
    id
    username
    permissions
    avatar
  }
}

# Query to get a vanity
query GetVanity($input: GetVanityInput!) {
  getVanity(input: $input) {
    id
    targetId
    type
    userId
  }
}

# Query to get panel stats
query GetPanelStats {
  bots {
    totalCount
  }
  tags {
    totalCount
  }
}